[package]
name = "static-site-generator"
version = "0.1.0"
authors = ["Ty Coghlan <Coghlan.Ty@gmail.com>"]

[dependencies]
Inflector = "0.11"
chrono = { version = "0.4", features = ["serde"] }
clap = "2.31"
serde = "1"
serde_derive = "1"
toml = "0.4"
